services:
  - type: web
    name: portfolio-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://siakha-kaba.onrender.com
      - key: PORT
        value: 3001
      - key: ADMIN_PASSWORD_HASH
        sync: false

  - type: web
    name: siakha-kaba
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://portfolio-backend-hzuc.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
